name: Build ForraCorp Apps EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # Use a real Windows server

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install customtkinter pillow pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        # This is the command line version of auto-py-to-exe
        pyinstaller --noconfirm --onefile --windowed --collect-all customtkinter --name "DigitalSentinel" main.py

    - name: Upload Result
      uses: actions/upload-artifact@v3
      with:
        name: Sentinel-Windows-Executable
        path: dist/DigitalSentinel.exe
